namespace FieldCure.AssistStudio.Runner.Models;

/// <summary>
/// Records a single execution of a Runner task.
/// </summary>
public sealed class TaskExecution
{
    /// <summary>Unique execution identifier.</summary>
    public required string Id { get; init; }

    /// <summary>Reference to the parent task.</summary>
    public required string TaskId { get; init; }

    /// <summary>Current execution status.</summary>
    public ExecutionStatus Status { get; set; }

    /// <summary>When execution started.</summary>
    public required DateTimeOffset StartedAt { get; init; }

    /// <summary>When execution completed (null if still running).</summary>
    public DateTimeOffset? CompletedAt { get; set; }

    /// <summary>Number of LLM rounds executed.</summary>
    public int RoundsExecuted { get; set; }

    /// <summary>One-line summary generated by the LLM after execution.</summary>
    public string? ResultSummary { get; set; }

    /// <summary>Error message if execution failed.</summary>
    public string? ErrorMessage { get; set; }

    /// <summary>Notification delivery status: sent, failed, or skipped.</summary>
    public string? NotificationStatus { get; set; }

    /// <summary>Relative path to the detailed execution log file. Format: logs/{Id}.json</summary>
    public string? LogPath { get; set; }
}
